version: '3'

services:
  redis_adapter:
    image: redis:5.0.4-alpine
    restart: always
  chat_rts:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_ENDPOINT=redis_adapter
    ports:
      - 8080:8080
    restart: always
